/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-19 18:22:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mail_005fsend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Bootstrap 101 Template</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 플러그인 참조 -->\r\n");
      out.write("<script src=\"js/plugin/form/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"js/plugin/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@media ( min-width : 980px) {\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tpadding-top: 60px;\r\n");
      out.write("\t\tpadding-bottom: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// submit 될 때, 유효성 검사 기능 수행  \r\n");
      out.write("\t\t$(\"#join_form\").validate({\r\n");
      out.write("\t\t\t// 유효성 검사 규칙  \r\n");
      out.write("\t\t\trules : {\r\n");
      out.write("\t\t\t\tsender : \"required\",\r\n");
      out.write("\t\t\t\treceiver : \"required\",\r\n");
      out.write("\t\t\t\tsubject : \"required\",\r\n");
      out.write("\t\t\t\tcontent : \"required\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t// 사용자에게 보여질 메시지  \r\n");
      out.write("\t\t\tmessages : {\r\n");
      out.write("\t\t\t\tsender : \"보내는 분의 메일 주소를 입력하세요.\",\r\n");
      out.write("\t\t\t\treceiver : \"받는 분의 메일 주소를 입력하세요.\",\r\n");
      out.write("\t\t\t\tsubject : \"제목을 입력하세요.\",\r\n");
      out.write("\t\t\t\tcontent : \"내용을 입력하세요.\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".sub-menu\">\r\n");
      out.write("\t<!-- 상단 고정메뉴 (검정) -->\r\n");
      out.write("\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"brand\">JSP Email 발송 연습</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--// 상단 고정메뉴 (검정) -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 내용영역 시작 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<form class=\"form-horizontal\" method=\"post\" action=\"SendMail.jsp\">\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t<strong>신규 회원 추가</strong>\r\n");
      out.write("\t\t\t\t</legend>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"sender\">보내는주소 <font\r\n");
      out.write("\t\t\t\t\t\tcolor='red'>*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"sender\" id=\"sender\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"input-block-level\" placeholder=\"보내는 분의 이메일 주소를 입력하세요.\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"receiver\">받는주소 <font\r\n");
      out.write("\t\t\t\t\t\tcolor='red'>*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"receiver\" id=\"receiver\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"input-block-level\" placeholder=\"받는 분의 이메일 주소를 입력하세요.\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"subject\">메일 제목<font\r\n");
      out.write("\t\t\t\t\t\tcolor='red'>*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"subject\" id=\"subject\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"input-block-level\" placeholder=\"이메일의 제목을 입력하세요.\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"content\">내용입력</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"content\" id=\"content\" class=\"ckeditor\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 버튼 영역 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-actions text-right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" value=\"메일보내기\" /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"reset\" class=\"btn\" value=\"다시작성\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--// 내용영역 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
